[package]
name = "emporium"
description = "WASM extension framework for Rust applications"
version = "0.0.1"
edition = "2024"
authors = ["Andy Terra <tech@andyterra.com>"]
license = "MIT"

[workspace]
members = [".", "core", "cli", "types", "examples/*"]

[workspace.dependencies]
emporium = { path = "." }
emporium-core = { path = "core" }
emporium-types = { path = "types" }
futures = "0.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[dependencies]
anyhow = "1.0"
emporium-core.workspace = true
emporium-types.workspace = true
flate2 = "1"
serde = { version = "1.0.208", features = ["serde_derive"] }
serde_json = "1.0.125"
tar = "0.4"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["fs"] }
toml = "0.9.8"
tracing = "0.1"
wasmtime = "43.0"
wasmtime-wasi = "43.0"
wasmtime-wasi-http = "43.0"

[dev-dependencies]
dotenvy = "0.15"

# [patch.crates-io]
# iced.git = "https://github.com/iced-rs/iced.git"

[patch."https://github.com/inboard-ai/emporium.git"]
emporium-core = { path = "core" }

# [patch.'https://github.com/inboard-ai/polygon.git']
# polygon = { path = "../../../polygon" }

# [patch.'https://github.com/inboard-ai/alphav.git']
# alphav = { path = "../../../alphav" }
